# Generated by Django 4.0.10 on 2023-12-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='donor',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_name',
            field=models.CharField(default='smith', max_length=30),
        ),
        migrations.AddField(
            model_name='donor',
            name='ssn',
            field=models.CharField(default='12345789', max_length=9),
        ),
    ]
