# Generated by Django 4.0.10 on 2023-12-07 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodbankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_expiry', models.DateField()),
                ('total_meals', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MealsFoodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('food_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbankapp.foodbankstock')),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meals')),
            ],
        ),
    ]
