# Generated by Django 4.0.10 on 2023-12-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='date',
            field=models.DateField(default='2023-12-07'),
        ),
    ]
